[package]
name = "office_reader_mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { version = "0.1.5", features = ["server"] }
calamine = "0.26.0"  # For Excel files - using older version to avoid yanked zip dependency
pdf-extract = "0.9.0"  # For PDF files
docx-rs = "0.4.7"  # For DOCX files
anyhow = "1.0.75"  # For error handling
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }

[dev-dependencies]
serde_json = "1.0.107"
tempfile = "3.20.0"
rmcp = { version = "0.1.5", features = ["client", "transport-child-process"] }
tokio = { version = "1.45.0", features = ["full"] }
