[target.x86_64-unknown-linux-gnu]
# Use the system linker for Linux (requires a Linux toolchain)
linker = "x86_64-linux-gnu-gcc"

[build]
# Default target for this project
target = "x86_64-pc-windows-msvc"

[env]
# Environment variables for cross-compilation
PKG_CONFIG_ALLOW_CROSS = "1"
